Newsweek Clone for Microverse
warblo001/Newsweek-Clone pull request #2
Opened 2020-10-27 08:39 UTC by warblo001

This is a project for the Microverse program.

In this project, I created a clone of the Newsweek.com site using the next front-end technologies :

The project has the following features:

- Responsiveness
- Bootstrap
- Flexbox and Floats
- Media queries for different screen sizes

2020-10-27 09:53 UTC, umairarshadbutt reviewed
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @warblo001
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes  👇.
- [ ] Navigation Links are missing in the navbar and main section. Please add the navigation links.
- [ ] Please remove the images of **LOGIN**, **SUBSCRIBE** and **Hamburger**. And design it by using HTML, CSS and Bootstrap.
- [ ] Please add the text in `alt` attribute. (see the inline comment)
- [ ] Screenshot is missing in README file. please add the screenshot of the landing page.

- [ ] **[OPTIONSL]:** You can use [Multi Devices Mockup](https://techsini.com/multi-mockup/index.php) for the screenshot.


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-10-27 09:53 UTC, umairarshadbutt commented on index.html
> +                    ><img src="assets/img/vs.jpg" alt="" />
Please add the text in `alt` attribute

2020-10-27 09:53 UTC, umairarshadbutt commented on index.html
> +          <img src="assets/img/login.jpg" alt="login" />
Please remove the image and design by HTML and CSS

2020-10-27 09:53 UTC, umairarshadbutt commented on index.html
> +          <img src="assets/img/login2.jpg" alt="login" />
Please remove the image and design by HTML and CSS

2020-10-27 09:53 UTC, umairarshadbutt commented on index.html
> +          <img src="assets/img/login3.jpg" alt="login" />
Please remove the image and design by HTML and CSS

2020-10-27 09:53 UTC, umairarshadbutt commented on index.html
> +        <div class="logo">
Please add the Navigation Link for Logo Image

2020-10-27 09:53 UTC, umairarshadbutt commented on index.html
> +                    <h3>
Please add the Navigation Link. (Please add the Navigation Link where we are using the pointer. Update the navigation link on the complete page)

2020-10-27 16:57 UTC, descholar-ceo requested changes
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @warblo001  :handshake: :handshake: :handshake: 
:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
## Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes]
- [ ] Since this project is mainly focusing on bootstrap, using display flex, or grid, in your own CSS/SCSS files is highly discouraged, try to replace them by bootstrap utility classes, [Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_classes_requirement.png), you can refer to the following links to learn how to use [grid with bootstrap](https://getbootstrap.com/docs/4.3/layout/grid/) and [flexbox](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options)
- [ ] In your CSS file, you have some properties that you have written again and again, please don't repeat yourself, you should either used utility classes and give them the propert you wish to apply, and then apply that class on any element you wish, or you can even group elements which are sharing the same property, [Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png)
- [ ] Implement all changes I suggested in inline comments in your codes

# [Optional changes]
- [ ] It's nice that you implemented the feedback you got of adding `alt` on all img tags, but make sure that all `alt` have descriptive text as their values e.g.: `alt=programmer's picture`
- [ ] Your commit messages should be in imperative mode or present tense, you should have used `Remove extra files, fix linters issues` instead of `Removed extra files, fixed linters issues`, refer [to this article for more details on how to write a good && professional commit message](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

If anything seems to be unclear to you, don't hesitate to contact me for more clarification slack: `@Mugirase Emmanuel` | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2020-10-27 16:57 UTC, descholar-ceo commented on assets/style.css
> +  height: 38px;
You are repeating yourself here, you have alredy use this `heigth: 38px;` on line 287, 1087, 1123 :point_right: create a utility class which have this property and apply it wherever you need this property

2020-10-27 16:57 UTC, descholar-ceo commented on assets/style.css
> +  background: #f72210;
You are repeating yourself here, you have alredy use this `background: #f72210;` on line 44, 122, 152, 161, 652, 873, 1085, 1121 point_right create a utility class which have this property and apply it wherever you need this property

2020-10-27 16:57 UTC, descholar-ceo commented on index.html
> +    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
It's not a good idea to load your script in head tag, it is nice to put this script loading at the end of you html codes inside body before body closing tag

2020-10-27 16:57 UTC, descholar-ceo commented on index.html
> +        <img src="assets/img/pesta.jpg" alt="s" />
The alt attribute should have a short descriptive text as its value

2020-10-28 10:00 UTC, umairarshadbutt approved these changes
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
### The [clone](https://adoring-benz-430942.netlify.app/) shows a good understanding and usage of Bootstrap. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
- The project has a descriptive README.md and is professionally done. Good job with that.
- Pull Request has a meaningful title and a short description.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @warblo001! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-10-28 10:02 UTC, merged